controller_joint_names: ['', 'finger_1_1_joint', 'finger_2_1_joint', 'finger_2_2_joint', 'finger_3_1_joint', 'finger_3_2_joint', 'finger_4_1_joint', 'finger_4_2_joint', 'finger_5_1_joint', 'finger_5_2_joint', ]
